### PR TITLE
Resource class update fix (rack collection)

### LINKED ISSUE #37: setting racks for a resource class fails
If I try to set new set of racks for a resource class:
curl -vX PUT -H 'Content-Type: application/json' -H 'Accept: application/json' -v -d  '
{
  "racks": [{"id": 3}]
}
' http://0.0.0.0:6385/v1/resource_classes/1

note that rack with id 3 is already added to the resoruce class, IOW by this request I want to delete all existing racks from rclass except rack 3.

I get this error:
2013-07-19 13:02:28.110 21187 TRACE tuskar.api.controllers.v1 Traceback (most recent call last):
2013-07-19 13:02:28.110 21187 TRACE tuskar.api.controllers.v1   File "/home/jprovazn/devel/tuskar/tuskar/api/controllers/v1.py", line 405, in put
2013-07-19 13:02:28.110 21187 TRACE tuskar.api.controllers.v1     resource_class)
2013-07-19 13:02:28.110 21187 TRACE tuskar.api.controllers.v1   File "/home/jprovazn/devel/tuskar/tuskar/db/sqlalchemy/api.py", line 160, in update_resource_class
2013-07-19 13:02:28.110 21187 TRACE tuskar.api.controllers.v1     session.add(rack)
2013-07-19 13:02:28.110 21187 TRACE tuskar.api.controllers.v1   File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1372, in add
2013-07-19 13:02:28.110 21187 TRACE tuskar.api.controllers.v1     self._save_or_update_state(state)
2013-07-19 13:02:28.110 21187 TRACE tuskar.api.controllers.v1   File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1381, in _save_or_update_state
2013-07-19 13:02:28.110 21187 TRACE tuskar.api.controllers.v1     self._save_or_update_impl(state)
2013-07-19 13:02:28.110 21187 TRACE tuskar.api.controllers.v1   File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1644, in _save_or_update_impl
2013-07-19 13:02:28.110 21187 TRACE tuskar.api.controllers.v1     self._update_impl(state)
2013-07-19 13:02:28.110 21187 TRACE tuskar.api.controllers.v1   File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1636, in _update_impl
2013-07-19 13:02:28.110 21187 TRACE tuskar.api.controllers.v1     self._attach(state)
2013-07-19 13:02:28.110 21187 TRACE tuskar.api.controllers.v1   File "/home/jprovazn/devel/tuskar/.tox/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1664, in _attach
2013-07-19 13:02:28.110 21187 TRACE tuskar.api.controllers.v1     % (mapperutil.state_str(state), state.key))
2013-07-19 13:02:28.110 21187 TRACE tuskar.api.controllers.v1 InvalidRequestError: Can't attach instance <Rack at 0x3b37c90>; another instance with key (<class 'tuskar.db.sqlalchemy.models.Rack'>, (3,)) is already present in this session.
2013-07-19 13:02:28.110 21187 TRACE tuskar.api.controllers.v1 
2013-07-19 13:02:28.112 21187 WARNING wsme.api [-] Client-side error: Invalid data
localhost.localdomain - - [19/Jul/2013 13:02:28] "PUT /v1/resource_classes/1 HTTP/1.1" 400 127524

### PR DESCRIPTION
**Pull request by jistr**
Fixes #37 and adds tests against regression.

Also I commented out the failing test, so that the test fail/pass information is actually helpful to the developer when changing code.

### CODE REVIEW

**Comment by mfojtik** [comment]
Love it! Thanks Jirka!

**Comment by mfojtik** [comment]
Oh can you please rebase?

**Comment by jistr** [comment]
Ok I'll remove the comment-out and rebase.

@jguiditta My opinion is that failing tests shouldn't be in master (and they wouldn't if we used some CI), because they don't provide value _at the moment_, but they hinder development experience (it's unpleasant to always check if the test fails are caused by my new code or old code, same goes for failing pep8). In an ideal case, failing tests would be kept in a separate WIP branch and merged into master together with a fix. Just my 2 cents :)

I think we should enable Travis and make things green when we have a bit of spare bandwidth.

**Comment by jistr** [comment]
Rebased. I also sneakily tweaked the tests and squashed the commit. Here's the diff:
http://fpaste.org/27167/45696821/

**Comment by jistr** [comment]
Thanks for the review guys! :)

**Comment by jguiditta** [comment]
@jistr Conceptually, I completely agree with you.  However, in this case, we started to 'make things right' by writing some tests to expose one of the errors you reported, and were then pulled away before we could finish getting this where we wanted, for purposes of being able to demo some of the things we are building.  I will fix the tests myself today, as I think I have a little breathing room.  In general, leaving broken tests can lead to 'broken window syndrome', so I certainly have no intention of them staying like this for any significant amount of time.  And +1 to using travis (or some other system preferred in python circles?) asap.

**Comment by jistr** [comment]
@jguiditta Thanks for explaining that :) Btw we use Travis for tuskarclient and we've had no trouble so far. https://travis-ci.org/tuskar/python-tuskarclient

**Pull request merged**
