### PR TITLE
Add more developer documentation.

### PR DESCRIPTION
**Pull request by jguiditta**
This is 'in process' stuff I have been writing up, so please don't merge it yet, even if you think these are the best directions you have ever read (yeah, right!).  I just want to get some feedback that I could incorporate tomorrow (otherwise I am gone for over a week, so this will sit).  Does it make sense to have all this stuff in the CONTRIBUTING file?  Perhaps a GETTING_STARTED or something else instead?  I suppose it could even go on the wiki, but I would rather have it right there for developers after the repo is cloned. I plan to add more info about models and perhaps a little on migrations, but the main thing I want in here is something on tests, which I currently have no idea how to write up.  This is the main part I want to look at tomorrow.  Any feedback/improvement suggestions welcome.

-j

### CODE REVIEW

**Comment by marios** [comment]
@jguiditta looks good to me. Since you've started the whole 'this is how you add a controller' section, I wonder if it makes sense to take that to conclusion and also mention the database side of things - i.e.:

```
tuskar/tuskar/db/sqlalchemy/api.py
and
tuskar/tuskar/db/sqlalchemy/model.py
```

You can also add to your 'dbsync' section with a mention of the migration file, currently at

```
tuskar/tuskar/db/sqlalchemy/migrate_repo/versions/001_init.py
```

all just suggestions - but this is very useful stuff in any case

marios

**Comment by jguiditta** [comment]
guys, thanks for the feedback.
@mfojtik I'll add that to the example, good idea.

@marios Agree, I'll definitely add that stuff in, though I am having a hard time getting myself to prioritize that over the test stuff, as I mentioned in my pull request message.  OTOH, it will probably be much quicker to add that, so I'll try to make sure I at least have that in by my eod today, then you guys who are here tomorrow can hopefully merge this, whether I have gotten the testing part in or not.

**Comment by jguiditta** [comment]
Ok, I have updated with the suggested additions.  I do not think I have enough information at this time to write a good howto on tests, though I am getting closer.  If someone could verify they feel the information I have thus far is correct, I would be happy to have this merged.  Otherwise, it is going to have to wait until next sprint.  I will likely just update the test portion later once I have a better understanding of it.

**Comment by markmc** [comment]
This is looking great, nice work Jay.

**Pull request merged**
