### PR TITLE
Fix resource_class links in Rack listings

### LINKED ISSUE #55: Racks.list returns different data than Racks.get
curl -H "Accept: application/json" http://0.0.0.0:6385/v1/racks/1
{"slots": 3, "subnet": "192.168.1.0/24", "name": "compute_1", "links": [{"href": "http://0.0.0.0:6385/v1/racks/1", "rel": "self"}], "resource_class": {"id": 1, "links": [{"href": "http://0.0.0.0:6385/v1/resource_classes/1", "rel": "self"}]}, "capacities": [{"name": "total_cpu", "value": "64"}, {"name": "total_memory", "value": "16384"}], "state": "unprovisioned", "chassis": {}, "location": "room d2, row 1", "nodes": [{"id": "b21af596-a08d-4626-b9a4-c0fff946abf9", "links": [{"href": "http://ironic.local:6543/v1/b21af596-a08d-4626-b9a4-c0fff946abf9", "rel": "node"}]}, {"id": "3f9ebbf8-f324-4476-b1d9-629163ff0ba0", "links": [{"href": "http://ironic.local:6543/v1/3f9ebbf8-f324-4476-b1d9-629163ff0ba0", "rel": "node"}]}, {"id": "b99d536d-71aa-4dcc-acd6-ee75df9f9fa2", "links": [{"href": "http://ironic.local:6543/v1/b99d536d-71aa-4dcc-acd6-ee75df9f9fa2", "rel": "node"}]}], "id": 1}

 curl -H "Accept: application/json" http://0.0.0.0:6385/v1/racks
[{"slots": 3, "subnet": "192.168.1.0/24", "name": "compute_1", "links": [{"href": "http://0.0.0.0:6385/v1/racks/1", "rel": "self"}], "resource_class": {"id": 2, "links": [{"href": "http://0.0.0.0:6385/v1/resource_classes/2", "rel": "self"}]}, "capacities": [{"name": "total_cpu", "value": "64"}, {"name": "total_memory", "value": "16384"}], "state": "unprovisioned", "chassis": {}, "location": "room d2, row 1", "nodes": [{"id": "b21af596-a08d-4626-b9a4-c0fff946abf9", "links": [{"href": "http://ironic.local:6543/v1/b21af596-a08d-4626-b9a4-c0fff946abf9", "rel": "node"}]}, {"id": "3f9ebbf8-f324-4476-b1d9-629163ff0ba0", "links": [{"href": "http://ironic.local:6543/v1/3f9ebbf8-f324-4476-b1d9-629163ff0ba0", "rel": "node"}]}, {"id": "b99d536d-71aa-4dcc-acd6-ee75df9f9fa2", "links": [{"href": "http://ironic.local:6543/v1/b99d536d-71aa-4dcc-acd6-ee75df9f9fa2", "rel": "node"}]}], "id": 1}, {"slots": 3, "subnet": "192.168.2.0/24", "name": "compute_2", "links": [{"href": "http://0.0.0.0:6385/v1/racks/2", "rel": "self"}], "resource_class": {"id": 2, "links": [{"href": "http://0.0.0.0:6385/v1/resource_classes/2", "rel": "self"}]}, "capacities": [{"name": "total_cpu", "value": "64"}, {"name": "total_memory", "value": "16384"}], "state": "unprovisioned", "chassis": {}, "location": "room d2, row 2", "nodes": [{"id": "a579b880-df22-4ec8-a714-d1fa72c33952", "links": [{"href": "http://ironic.local:6543/v1/a579b880-df22-4ec8-a714-d1fa72c33952", "rel": "node"}]}, {"id": "b24a58a7-00b3-4378-9dd6-e292e9f6fb07", "links": [{"href": "http://ironic.local:6543/v1/b24a58a7-00b3-4378-9dd6-e292e9f6fb07", "rel": "node"}]}, {"id": "2fff8303-6e0e-461f-8866-cedce660dffd", "links": [{"href": "http://ironic.local:6543/v1/2fff8303-6e0e-461f-8866-cedce660dffd", "rel": "node"}]}], "id": 2}, {"slots": 3, "subnet": "192.168.3.0/24", "name": "not_compute", "links": [{"href": "http://0.0.0.0:6385/v1/racks/3", "rel": "self"}], "resource_class": {"id": 2, "links": [{"href": "http://0.0.0.0:6385/v1/resource_classes/2", "rel": "self"}]}, "capacities": [{"name": "total_cpu", "value": "64"}, {"name": "total_memory", "value": "16384"}], "state": "unprovisioned", "chassis": {}, "location": "room d2, row 3", "nodes": [{"id": "07abf8b9-8cfa-4acc-abbb-e1984e8d13c5", "links": [{"href": "http://ironic.local:6543/v1/07abf8b9-8cfa-4acc-abbb-e1984e8d13c5", "rel": "node"}]}], "id": 3}]

notice that "compute_1" has relation with resource_class 1 via get, via post it has relation with resource_class 2 (it's broken also in other racks)

Correct information are those obtained via get

### PR DESCRIPTION
**Pull request by jistr**
Fixes https://github.com/tuskar/tuskar/issues/55

### CODE REVIEW

**Comment by mfojtik** [comment]
Actually the Travis failure looks serious ;-) So please fix that before merge :-)

**Comment by jistr** [comment]
So, this one was more interesting than it seemed in the beginning.

We had an inconsistency in printing null associations on Rack. If the chassis was not present, it would print out as `"chassis": {}` in the JSON. If the resource_class was not present, it would not print out in the JSON at all. This pull request changes it so that it prints out as `"resource_class": {}`, the same way as chassis. Will this break the UI in any way?

Fixing this bug and keeping the original behavior would be possible, however i'd have to do some more funky stuff with the code there.

**Comment by mfojtik** [comment]
+1 I think we should be consistent in displaying those associations.

**Comment by jistr** [comment]
V3 that should hopefully do it. Please take a look, i had to rearrange the whole method to allow passing resource_class as a keyword argument that is sometimes present and sometimes not (in order to preserve current API behavior).

Thanks for writing the Rack tests btw, they helped.

**Comment by mfojtik** [comment]
@jistr this looks great! thanks! is this mergeable without breaking the UI stuff?

**Comment by jistr** [comment]
@mfojtik Yes I think it is. It shouldn't change the resource class JSON format at all.

**Comment by jistr** [comment]
Thanks for the review :)

**Pull request merged**
