### PR TITLE
Refactor tests and api files

### PR DESCRIPTION
**Pull request by mtaylor**
This splits out much of the code that was previously in large files into multiple files.  This should reduce merge conflicts and simplify the code.

This code does introduce a number of pep8 issues.  To be cleaned up in a subsequent patchset.

### CODE REVIEW

**Comment by tomassedovic** [comment]
Looks good to me, but someone more familiar with the codebase should look at it too before we merge this.

**Comment by mfojtik** [comment]
Just a quick nit: Can we use plural in controller file names? I like more:

resource_classes.py instead of resource_class.py

Also I dunno if using 'controllers' sub directory is not 'rails' pattern that many python devs are not famialiar with ;-) But I like that and I'm perfectly fine with that.

**Comment by petrblaho** [comment]
One issue I have with splitting classes into separate files is that it produces a bunch of

```
"H302  import only modules.'from tuskar.api.controllers.v1.types.link import Link' does not import a module"
```

pep8 errors.

These cannot be avoided due to our need to import classes from files/modules.

Some openstack projects ignore some pep8 error, including H302:
https://github.com/openstack/tempest/blob/master/tox.ini#L88
https://github.com/openstack/horizon/blob/master/tox.ini#L46
https://github.com/openstack/nova/blob/master/tox.ini#L48
https://github.com/openstack/trove/blob/master/tox.ini#L36

I think we should decide step-by-stepin the future what errors to ignore and what to comply with
but I think we can easily ignore H302 - we should just create issue or pull request with that config change.

**Comment by mfojtik** [comment]
IMHO we should ignore the same errors as Nova or other Openstack project do.

**Comment by petrblaho** [comment]
@mfojtik yeah but they do not have the same set of error they ignore....

Right now we are ignoring just one error and with H302 we will be ignoring 2...
Some openstack projects has a full line of ignored errors in configs.

I would suggest that we should ignore the minimum we have to and hold discussion and look for other openstack projects configs before adding new one to ignore list.

@mtaylor ACK for me (but I like @mfojtik's suggestion for plural names)

**Comment by mtaylor** [comment]
Actually we should fix these errors.

|from tuskar.api.controllers.v1.types.link import Link|

Actually imports a Class not a module, you can get round this by doing this:

|from tuskar.api.controllers.v1.types import link

Link = link.Link
|

**Comment by petrblaho** [comment]
> Actually we should fix these errors.
> |from tuskar.api.controllers.v1.types.link import Link
> | Actually imports a Class not a module, you can get round this by doing this:
> |from tuskar.api.controllers.v1.types import link Link = link.Link

That's good... so I would merge this PR and then start working on resolving one pep8 issue at time.

**Comment by tomassedovic** [comment]
I think I saw a comment directive to silence some pyflake errors somewhere. Perhaps we could do the same thing with pep8?

I'll note this: `from foo.bar import Baz` is not a violation of PEP8:

http://www.python.org/dev/peps/pep-0008/#imports

Martyn's suggestion would work but it effectively does the same thing only with more code (and therefore more prone to errors) and the only reason is to shut up a stupid tool.

This is not an actual legitimate error.

**Comment by petrblaho** [comment]
That import error we are talking about is not in fact violation of PEP8 - it is violation of coding style used in openstack projects.

There is a set of pep8 plugins (as I understand) at https://github.com/openstack-dev/hacking introducing these kind of Hxxx "pep8" errors - see https://github.com/openstack-dev/hacking/blob/master/hacking/core.py#L59-L68

@tomassedovic - we can just ignore errors in pep8 settings in tox.ini.

According to https://pypi.python.org/pypi/pep8 and https://pypi.python.org/pypi/flake8 you can use `# NOQA` or `# nopep8` comment for ignoring that line in pep8 tests. (Do not forget at least two spaces before inline comment or you will produce E261 with your comment :-))

**Comment by tomassedovic** [comment]
Ah, I see.

In that case I suggest to relax this requirement for the `__init__.py` files where this is perfectly legitimate (and would result in a less readable and harder to maintain code) and conforming to the convention everywhere else.

**Comment by petrblaho** [comment]
If everyone is ok with subsequent solving of pep8 issues as @mtaylor wrote in PR description
and if everyone is ok (now) with singular names (@mfojtik pointed out above)
I would suggest that we can merge.

After merge I will make a PR for inline comments on lines with H302 problems in `__init__.py` files as @tomassedovic suggested (I like this way) and continue with solving pep8 errors.

**Comment by tomassedovic** [comment]
Sounds good to me.

**Comment by mfojtik** [comment]
:+1:

**Comment by jistr** [comment]
I'm also for the `# nopep8` solution.

**Pull request merged**
