### PR TITLE
Status code 500 instead of 404 for deleting non-existent Rack

### PR DESCRIPTION
**Pull request by jguiditta**
Similar to #18, occurs with DELETE request on e.g. `/v1/racks/123` when that rack doesn't exist.

### CODE REVIEW

**Comment by mfojtik** [comment]
ACK!.

@jguiditta can you please rebase this?

**Comment by jguiditta** [comment]
Going to merge this myself, since @mfojtik already acked it pending a rebase.  Travis has run and failed, but this is because the heat client seems to require a real server, so we need to stub that out, but this is out of scope for this pull request.  For the record, the remaining fail on travis is:

```
Starting new HTTP connection (1): 10.34.32.181
Server-side error: "Authorization Failed: ". Detail:
```

 This is around line 570 of the referenced travis build.  Apparently none of us have gotten this error because we have access to that ip address.

**Pull request merged**
