### PR TITLE
Changes format and indents for pep8

### PR DESCRIPTION
**Pull request by petrblaho**
This is changes in code formating and indentation
to comply with pep8 standard.

It follows current setting in tox.ini for pep8 (flake8).

I skipped errors like:
- F821 undefined name
- H302 import only modules

This pull request is first to prepare tuskar for CI (TravisCI)
and for better developer experience as @jistr noted at #47

### CODE REVIEW

**Comment by jguiditta** [comment]
Hmm, this gets me 2 more test errors than I get on master:

```
FAIL: tuskar.tests.test_v1.TestResourceClasses.test_update_name_only
FAIL: tuskar.tests.test_v1.TestResourceClasses.test_update_racks
```

**Comment by petrblaho** [comment]
On Tue, Jul 23, 2013 at 06:54:09AM -0700, jguiditta wrote:

> Hmm, this gets me 2 more test errors than I get on master:
> 
> FAIL: tuskar.tests.test_v1.TestResourceClasses.test_update_name_only
> FAIL: tuskar.tests.test_v1.TestResourceClasses.test_update_racks
> 
> —
> Reply to this email directly or view it on GitHub.*

Looking on them... thanks for reporting...

## 

Petr Blaho, pblaho@redhat.com
Software Engineer, CloudForms

**Comment by petrblaho** [comment]
Repaired...

**Comment by jguiditta** [comment]
Far fewer pep8 infractions, and tests are now back to where they were before this patch, so good improvement, ACK!

**Pull request merged**
