### PR TITLE
Solve pep8 H302 issues

### PR DESCRIPTION
**Pull request by petrblaho**

### CODE REVIEW

**Comment by petrblaho** [comment]
I am opening this pull request to fire a discussion how we should handle `H302  import only modules.` pep8 error.

As discussed in #101 I now added `# nopep8` comment at the end of lines in `__init__.py` files under `tuskar/api/controllers` dir.
This cleared 15 of 51 H302 occurencies.

Others are spreaded among these files:

```
./tuskar/api/controllers/v1/controller.py
./tuskar/api/controllers/v1/data_center.py
./tuskar/api/controllers/v1/flavor.py
./tuskar/api/controllers/v1/rack.py
./tuskar/api/controllers/v1/resource_class.py
./tuskar/api/controllers/v1/types/capacity.py
./tuskar/api/controllers/v1/types/chassis.py
./tuskar/api/controllers/v1/types/flavor.py
./tuskar/api/controllers/v1/types/link.py
./tuskar/api/controllers/v1/types/node.py
./tuskar/api/controllers/v1/types/rack.py
./tuskar/api/controllers/v1/types/relation.py
./tuskar/api/controllers/v1/types/resource_class.py
./tuskar/heat/client.py
```

The half of main services in openstack ignores H302 in tox.ini file,
others comply with it.

Our code now does this kind of import:

``` python
from tuskar.api.controllers.v1.controller import Controller
```

where `Controller` is a class used in code as usual.

So the question is whether we will do

``` python
from tuskar.api.controllers.v1 import controller
```

and in the code use `controller.Controller`

or we will do

``` python
from tuskar.api.controllers.v1 import controller
Controller = controller.Controller
```

as @mtaylor pointed out in discussion #101 

or we can add `# nopep8` to each of these lines to disable check on them
(this would be the case all but 2 occurencies IIRC)

or we will disable H302 in `tox.ini`.

**Comment by mtaylor** [comment]
I say we do what Nova does in this case and ignore these errors in the tox.ini

https://github.com/openstack/nova/blob/master/tox.ini#L50

**Comment by jistr** [comment]
@mtaylor +1

**Comment by petrblaho** [comment]
I am ok with ignoring H302 in pep8 check.
Will prepare new pull request soon.

**Comment by mtaylor** [comment]
This is superseeded by #107 which sets ignore H302 in tox.ini as discussed above.

**Pull request closed without merging**
