### PR TITLE
Base documentation organization

### PR DESCRIPTION
**Pull request by jistr**
This is an updated version of @tzumainn's pull request https://github.com/tuskar/tuskar/pull/94 so that the build passes.

(We want to keep files in reStructured text to adhere to Python conventions.)

### CODE REVIEW

**Comment by jistr** [comment]
Do not merge, pandoc generated some funny stuff. It will need manual fixing.

**Comment by marios** [comment]
OK - I am going to go ahead and push #93 then which has a small fix in readme - can you include that when you send again?

EDIT - on request I won't merge #93 yet until this stuff is sorted

**Comment by jistr** [comment]
Ready for review.

**Comment by marios** [comment]
i think this may need rebase? I am getting:

```
[m@m tuskar]$ git checkout master 
Switched to branch 'master'
[m@m tuskar]$ github_pull 
Enter passphrase for key '/home/m/.ssh/id_rsa': 
Already up-to-date.
Enter passphrase for key '/home/m/.ssh/id_rsa': 
Already up-to-date.
[m@m tuskar]$ git checkout pull_95 
Switched to branch 'pull_95'
[m@m tuskar]$ git rebase master
Current branch pull_95 is up to date.
[m@m tuskar]$ curl https://github.com/tuskar/tuskar/pull/95.patch | git am 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20777  100 20777    0     0   9855      0  0:00:02  0:00:02 --:--:-- 17667
Applying: Updated Tuskar README
Applying: Base documentation organization
error: patch failed: README.rst:3
error: README.rst: patch does not apply
Patch failed at 0002 Base documentation organization
The copy of the patch that failed is found in:
   /home/m/Documents/WORK/NewEclipsey/Github/Tuskar/tuskar/.git/rebase-apply/patch
When you have resolved this problem, run "git am --resolved".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```

**Pull request merged**
